/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:568766:
  appc.background(230);
} //_CODE_:window1:568766:

public void restart_click(GButton source, GEvent event) { //_CODE_:restart:320607:
  raceMode = false; // Cancel out race
  racePhase = 0; // Reset race phase, Important for race logic
  sorter.reset(); // Reset (used for normal not race)
} //_CODE_:restart:320607:

public void start_click(GButton source, GEvent event) { //_CODE_:start:738163:
  if (!raceMode) {
    // Make sure no changes are made during race
    sorter.toggleSorting();
  }
} //_CODE_:start:738163:

public void bubbleSortButton_click(GButton source, GEvent event) { //_CODE_:bubbleSortButton:552353:
  if (!raceMode) {
    sorter.setAlgorithm(0);
  }
} //_CODE_:bubbleSortButton:552353:

public void insertionSortButtonClick(GButton source, GEvent event) { //_CODE_:insertionSortButton:297208:
  if (!raceMode) {
    sorter.setAlgorithm(1);
  }
} //_CODE_:insertionSortButton:297208:

public void mergeSortButtonClick(GButton source, GEvent event) { //_CODE_:mergeSortButton:906100:
  if (!raceMode) {
    sorter.setAlgorithm(2);
  }
} //_CODE_:mergeSortButton:906100:

public void arraySizeSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:arraySizeSlider:231801:
  if (!raceMode) {
    arraySize = source.getValueI();
    sorter = new Sorter(arraySize, height - 100);
  }
  
} //_CODE_:arraySizeSlider:231801:

public void fpsSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:fpsSlider:976330:
  setFPS = source.getValueI();
  frameRate(setFPS);
} //_CODE_:fpsSlider:976330:

public void quickSortButtonClicked(GButton source, GEvent event) { //_CODE_:quickSortButton:536758:
  if (!raceMode) {
    sorter.setAlgorithm(3);
  }
} //_CODE_:quickSortButton:536758:

public void bogoSortButtonClicked(GButton source, GEvent event) { //_CODE_:bogoSortButton:401517:
  if (!raceMode) {
    sorter.setAlgorithm(4);
  }
} //_CODE_:bogoSortButton:401517:

public void algo1Changed(GDropList source, GEvent event) { //_CODE_:algoDropdown1:746276:
  raceAlgo1 = algoDropdown1.getSelectedIndex();
} //_CODE_:algoDropdown1:746276:

public void algo2Changed(GDropList source, GEvent event) { //_CODE_:algoDropdown2:860288:
  raceAlgo2 = algoDropdown2.getSelectedIndex();
} //_CODE_:algoDropdown2:860288:

public void raceButtonClicked(GButton source, GEvent event) { //_CODE_:raceButton:340994:
  raceMode = true;
  racePhase = 0;
  sorter.reset();
  sorter.setAlgorithm(raceAlgo1);
  sorter.sorting = true;
} //_CODE_:raceButton:340994:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 520, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  restart = new GButton(window1, 135, 15, 80, 30);
  restart.setText("Restart");
  restart.addEventHandler(this, "restart_click");
  start = new GButton(window1, 25, 15, 80, 30);
  start.setText("Start");
  start.addEventHandler(this, "start_click");
  bubbleSortButton = new GButton(window1, 20, 55, 80, 30);
  bubbleSortButton.setText("Bubble Sort");
  bubbleSortButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  bubbleSortButton.addEventHandler(this, "bubbleSortButton_click");
  insertionSortButton = new GButton(window1, 70, 135, 100, 30);
  insertionSortButton.setText("Insertion Sort");
  insertionSortButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  insertionSortButton.addEventHandler(this, "insertionSortButtonClick");
  mergeSortButton = new GButton(window1, 35, 95, 80, 30);
  mergeSortButton.setText("Merge Sort");
  mergeSortButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  mergeSortButton.addEventHandler(this, "mergeSortButtonClick");
  arraySizeSlider = new GCustomSlider(window1, 10, 210, 100, 80, "grey_blue");
  arraySizeSlider.setShowValue(true);
  arraySizeSlider.setLimits(50, 4, 150);
  arraySizeSlider.setNbrTicks(10);
  arraySizeSlider.setShowTicks(true);
  arraySizeSlider.setNumberFormat(G4P.INTEGER, 0);
  arraySizeSlider.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  arraySizeSlider.setOpaque(false);
  arraySizeSlider.addEventHandler(this, "arraySizeSliderChanged");
  fpsSlider = new GCustomSlider(window1, 130, 210, 100, 80, "grey_blue");
  fpsSlider.setShowValue(true);
  fpsSlider.setLimits(30, 1, 240);
  fpsSlider.setNbrTicks(6);
  fpsSlider.setShowTicks(true);
  fpsSlider.setNumberFormat(G4P.INTEGER, 0);
  fpsSlider.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  fpsSlider.setOpaque(false);
  fpsSlider.addEventHandler(this, "fpsSliderChanged");
  sizeLabel = new GLabel(window1, 20, 180, 80, 20);
  sizeLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  sizeLabel.setText("Array Size");
  sizeLabel.setOpaque(false);
  fpsLabel = new GLabel(window1, 130, 180, 100, 20);
  fpsLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  fpsLabel.setText("Sorting Speed");
  fpsLabel.setOpaque(false);
  quickSortButton = new GButton(window1, 125, 95, 80, 30);
  quickSortButton.setText("Quick Sort");
  quickSortButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  quickSortButton.addEventHandler(this, "quickSortButtonClicked");
  bogoSortButton = new GButton(window1, 115, 55, 100, 30);
  bogoSortButton.setText("Bogo Sort");
  bogoSortButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  bogoSortButton.addEventHandler(this, "bogoSortButtonClicked");
  algoDropdown1 = new GDropList(window1, 20, 350, 90, 120, 5, 10);
  algoDropdown1.setItems(loadStrings("list_746276"), 1);
  algoDropdown1.addEventHandler(this, "algo1Changed");
  algoDropdown2 = new GDropList(window1, 130, 350, 90, 120, 5, 10);
  algoDropdown2.setItems(loadStrings("list_860288"), 0);
  algoDropdown2.addEventHandler(this, "algo2Changed");
  Racing = new GLabel(window1, 60, 300, 120, 20);
  Racing.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Racing.setText("Racing Options");
  Racing.setOpaque(false);
  raceButton = new GButton(window1, 80, 480, 80, 30);
  raceButton.setText("RACE!");
  raceButton.addEventHandler(this, "raceButtonClicked");
  instructions = new GLabel(window1, 30, 327, 180, 20);
  instructions.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  instructions.setText("(pick 2 algos then click race)");
  instructions.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton restart; 
GButton start; 
GButton bubbleSortButton; 
GButton insertionSortButton; 
GButton mergeSortButton; 
GCustomSlider arraySizeSlider; 
GCustomSlider fpsSlider; 
GLabel sizeLabel; 
GLabel fpsLabel; 
GButton quickSortButton; 
GButton bogoSortButton; 
GDropList algoDropdown1; 
GDropList algoDropdown2; 
GLabel Racing; 
GButton raceButton; 
GLabel instructions; 
