/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:568766:
  appc.background(230);
} //_CODE_:window1:568766:

public void restart_click(GButton source, GEvent event) { //_CODE_:restart:320607:
  resetArray();
} //_CODE_:restart:320607:

public void start_click(GButton source, GEvent event) { //_CODE_:start:738163:
  sorting = !sorting;
} //_CODE_:start:738163:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 480, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  restart = new GButton(window1, 20, 20, 80, 30);
  restart.setText("Restart");
  restart.addEventHandler(this, "restart_click");
  start = new GButton(window1, 20, 60, 80, 30);
  start.setText("Start");
  start.addEventHandler(this, "start_click");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton restart; 
GButton start; 
